#!/usr/bin/python

import json
import requests


def fetch_data():
    keyfile = open('/home/maurn/.config/polybar/api-key', 'r')
    api_key = keyfile.readline().rstrip('\n')
    url = "https://api.torn.com/user/?selections=travel,bars,cooldowns&key=%s" % api_key

    request = requests.get(url)
    return json.loads(request.text)


def get_status(data):
    status = ''
    destination = data['travel']['destination']
    time_left = data['travel']['time_left']

    if (destination == 'Torn') and (time_left == 0):
        energy_bar = data['energy']['current']
        nerve_bar = data['nerve']['current']
        drug_cooldown = data['cooldowns']['drug']

        energy = energy_bar if energy_bar < data['energy']['maximum'] else color('FULL', 'f80')
        nerve = nerve_bar if nerve_bar < data['nerve']['maximum'] else color('FULL', 'ff0')
        drugs = ' '+format_time(drug_cooldown) if drug_cooldown > 0 else color(' !!DRUGS!!', 'f00')

        status = '{} {} {}'.format(energy, nerve, drugs)
        return status

    if time_left > 0:
        status = ' {} in {}'.format(destination, format_time(time_left))
    else:
        status = color(destination.upper(), 'f00')

    return status


def format_time(seconds):
    minutes, seconds = divmod(seconds, 60)
    hour, minutes = divmod(minutes, 60)

    return '{}h {}m'.format(hour, minutes)


def color(string, hex_code):
    return '%{{F#{0}}}{1}%{{F-}}'.format(hex_code, string)


try:
    print(get_status(fetch_data()))
except requests.exceptions.RequestException:
    print('')
