#!/usr/bin/python

import json
import requests


def fetch_data():
    with open('/home/maurn/.config/polybar/api-key', 'r') as keyfile:
        api_key = keyfile.readline().rstrip('\n')

    url = "https://api.torn.com/user/?selections=basic,travel,bars,cooldowns&key={}".format(api_key)
    request = requests.get(url)
    return json.loads(request.text)


def get_summary(data):
    summary = ''
    destination = data['travel']['destination']
    time_left = data['travel']['time_left']

    if (destination == 'Torn') and (time_left == 0):
        current_status = data['status'][0]
        energy_bar = data['energy']['current']
        nerve_bar = data['nerve']['current']
        drug_cooldown = data['cooldowns']['drug']

        status_words = current_status.split()
        final_status = ''
        if(len(status_words) > 1):
            final_status = status_words[1]
        else:
            final_status = status_words[0];

        status_icons = {'okay': color('', '0f0'),
                        'hospital': '',
                        'jail': ''}

        stat = status_icons[final_status.lower()]
        energy = energy_bar if energy_bar < data['energy']['maximum'] else color('FULL', 'f80')
        nerve = nerve_bar if nerve_bar < data['nerve']['maximum'] else color('FULL', 'ff0')
        drugs = format_time(drug_cooldown) if drug_cooldown > 0 else color(' DRUGS', 'f00')

        summary = '{} {}  {}   {}'.format(stat, energy, nerve, drugs)
        return summary

    if time_left > 0:
        summary = ' {} in {}'.format(destination, format_time(time_left))
    else:
        summary = ' ' + color(destination.upper(), 'f00')

    return summary


def format_time(seconds):
    minutes, seconds = divmod(seconds, 60)
    hour, minutes = divmod(minutes, 60)

    return '{}h {}m'.format(hour, minutes)


def color(string, hex_code):
    return '%{{F#{0}}}{1}%{{F-}}'.format(hex_code, string)


try:
    print(get_summary(fetch_data()))
except:
    print('')
